# Bitte NICHT verändern!
ConfigVersion: ${project.version}

# Bot Token; du weißt nicht, was das ist? Schau dir das Video auf der Pluginseite an!
BotToken: "BOTTOKEN"

# Channel/Kanal Verknüpfung zwischen Minecraft und Discord
# Die Syntax ist Channels: {"Ingame Channelname": "numerische Kanal ID von Discord", "anderer ingame Channelname": "andere numerische Kanal ID von Discord"}
# Das erste angegebene Kanal-Paar in dieser Konfigurationsoption ist automatisch der Hauptkanal, wird genutzt für Spieler Betreten/Verlassen/Tode/Erungenschaften/etc Meldungen
#
Channels: {"global": "NUMERISCHECHANNELID"}

# ConsoleChannel; benötigt eine numerische Kanal ID (NICHT DEN NAMEN!), zum Deaktivieren auf "" setzen
DiscordConsoleChannelId: "NUMERISCHECHANNELID"

# Debug Optionen, nicht anfassen bis wirklich benötigt
DebugLevel: 0
CancelConsoleCommandIfLoggingFailed: true
DontSendCanceledChatEvents: true

# Verbindung mit anderen Plugins und deren Formatierung
#
# mögliche Format-Platzhalter sind: %channelcolor%, %channelname%, %channelnickname%, %message%
#
ChatChannelHookMessageFormat: "%channelcolor%[%channelnickname%]&r %message%"
EnabledPluginHooks: [HeroChat, LegendChat, LunaChat, TownyChat, VentureChat]

# Spielinformation, dies setzt den "Spielt ______" Status des Bots, zum Deaktivieren auf "" setzten
DiscordGameStatus: "Minecraft"

# Chatchannel Einstellungen
# Der Chatchannel ist der Text-Kanal, in den alle ingame Nachrichten gesendet werden und von dem aus
# alle anderen Nachrichten zurück ins Spiel geschickt werden
#
# DiscordChatChannelDiscordToMinecraft: Legt fest ob Nachrichten von Discord nach Minecraft geschickt werden sollen
# DiscordChatChannelMinecraftToDiscord: Legt fest ob Nachrichten von Minecraft nach Discord geschickt werden sollen
# DiscordChatChannelTruncateLength: Maximale Länge einer Nachricht, die von Discord nach Minecraft geschickt wird
# DiscordChatChannelPrefix: nur Nachrichten mit diesem Pfäfix werden von Minecraft nach Discord geschickt (z.B. "!")
# DiscordChatChannelRolesAllowedToUseColorCodesInChat: Liste mit Gruppen, die bei Nachrichten von Discord nach Minecraft Farbformatierungscodes benutzen dürfen
# DiscordChatChannelBroadcastDiscordMessagesToConsole: Legt fest, ob Nachrichten von Discord nach Minecraft zusätzlich an die Konsole geschickt werden sollen
# DiscordChatChannelColorTranslations: Hexadezimale Darstellung der Discord-Gruppen-Farben mit ihrem jeweiligen ingame Equivalent
#
DiscordChatChannelDiscordToMinecraft: true
DiscordChatChannelMinecraftToDiscord: true
DiscordChatChannelTruncateLength: 100
DiscordChatChannelPrefix: ""
DiscordChatChannelRolesAllowedToUseColorCodesInChat: ["Developer", "Owner", "Admin", "Moderator"]
DiscordChatChannelBroadcastDiscordMessagesToConsole: true
DiscordChatChannelColorTranslations: {
  "99AAB5": "&f",
  "1ABC9C": "&a",
  "2ECC71": "&a",
  "3498DB": "&3",
  "9B59B6": "&5",
  "E91E63": "&d",
  "F1C40F": "&e",
  "E67E22": "&6",
  "E74C3C": "&c",
  "95A5A6": "&7",
  "607D8B": "&8",
  "11806A": "&2",
  "1F8B4C": "&2",
  "206694": "&1",
  "71368A": "&5",
  "AD1457": "&d",
  "C27C0E": "&6",
  "A84300": "&6",
  "992D22": "&4",
  "979C9F": "&7",
  "546E7A": "&8"
}

# ConsolChannel Einstellungen
# Der ConsoleChannel ist der Text-Kanal, der direkt mit der Minecraft Konsole verbunden ist und über den
# Serverbefehle abgeschickt werden können, welche Zeile für Zeile ausgewertet werden
#
# DiscordConsoleChannelLogRefreshRateInSeconds: Zeit in Sekunden zwischen dem Senden von neuen Zeilen der Konsole
# DiscordConsoleChannelUsageLog: Datei, die alle Befehle der Spieler im ConsoleChannel loggt
# DiscordConsoleChannelBlacklistActsAsWhitelist: Gibt an, ob die Blacklist für Befehle als Whitelist fungieren soll
# DiscordConsoleChannelBlacklistedCommands: Befehle, die über den ConsoleChannel nicht ausführbar sein sollen
# DiscordConsoleChannelDoNotSendPhrasesActsAsWhitelist: Gibt an, ob die DoNotSendPhrases Liste als Whitelist fungieren soll (nur die angegebenen Phrasen können verschickt werden)
# DiscordConsoleChannelDoNotSendPhrases: Phrasen, die nicht über die Konsole verschickt werden können
# DiscordConsoleChannelRegexFilter: Regex Filter, der über Befehlsausgaben gelegt wird (z.B. "\[\d+:\d+:\d+ \w+\]: " entfernt Zeitstempel)
# DiscordConsoleChannelRegexReplacement: Vom Regex Filter erfasste Ausgaben werden mit dieser Zeichenkette ersetzt
# DiscordConsoleChannelLevels: Log-Level, die an den ConsoleChannel gesendet werden
#
# DiscordConsoleChannelFormat: Formatierung der einzelnen Ausgabezeilen der Konsole
# %date% = Aktuelles Datum und Uhrzeit
# %level% = Nachrichtenlevel (info/warn/error)
# %line% = Der ursprüngliche Ausgabetext der gesendeten Zeile
#
DiscordConsoleChannelLogRefreshRateInSeconds: 5
DiscordConsoleChannelUsageLog: "DiscordConsole.log"
DiscordConsoleChannelBlacklistActsAsWhitelist: false
DiscordConsoleChannelBlacklistedCommands: ["?", "op", "deop"]
DiscordConsoleChannelDoNotSendPhrasesActsAsWhitelist: false
DiscordConsoleChannelDoNotSendPhrases: ["Async Chat Thread"]
DiscordConsoleChannelRegexFilter: ""
DiscordConsoleChannelRegexReplacement: ""
DiscordConsoleChannelLevels: ["info", "warn", "error"]
DiscordConsoleChannelFormat: "[%date% %level%] %line%"

# Minecraft <-> Discord Formatierung
#
# DiscordToMinecraftChatMessageFormat: Das Format für Nachrichten von Discord nach Minecraft
# DiscordToMinecraftChatMessageFormatNoRole: Format für Nachrichten von Discord nach Minecraft, wenn dem Spieler keine Rollen zugeteilt sind
# %allroles% = Alle Rollen des Senders kombiniert mit DiscordToMinecraftAllRolesSeparator dazwischen
# %message% = Inhalt der Nachricht
# %toprole% = Höchste Rolle des Senders
# %toprolecolor% = Farbe der höchstwertigen Rolle, der der Sender angehört
# %username% = Name des Serders in Discord
#
# DiscordToMinecraftAllRolesSeparator: Der Separator der zwischen den einzelnen Rollen von %allroles% eingesetzt wird
#
# MinecraftChatToDiscordMessageFormat: Format für Nachrichten von Minecraft nach Discord
# %displayname% = Anzeigename des Senders
# %message% = Inhalt der Nachricht
# %primarygroup% = Name der Hauptgruppe des Senders
# %username% = Unveränderter Name des Senders
# %world% = Name der Welt in der sich der Sender befindet
# %worldalias% = Alias der Welt, in der sich der Sender befindet innerhalb von Multiverse-Core
# %date% = Datum der Nachricht z.B. "Fri Apr 01 12:00:00 PDT 2016"
#
DiscordToMinecraftChatMessageFormat: "[&bDiscord &r| %toprolecolor%%toprole%&r] %username% » %message%"
DiscordToMinecraftChatMessageFormatNoRole: "[&bDiscord&r] %username% » %message%"
DiscordToMinecraftAllRolesSeparator: " | "
MinecraftChatToDiscordMessageFormat: "**%primarygroup%** %displayname% » %message%"
MinecraftChatToDiscordMessageFormatNoPrimaryGroup: "%displayname% » %message%"

# Chatchannel Befehlsausführung
# Diese Optionen steuern die Möglichkeit Befehle über ein spezielles Präfix wie "!c kick Notch"
# in einem verbundenen Chatchannel auszuführen
#
# DiscordChatChannelConsoleCommandEnabled: Gibt an, ob Konsolenbefehle in Chatchanneln genutzt werden können
# DiscordChatChannelConsoleCommandNotifyErrors: Gibt an, ob der Sender über fehlende Berechtigungen informiert werden soll, wenn er diese nicht hat
# DiscordChatChannelConsoleCommandPrefix: Prefix zur Erkennung von Konsolenbefehlen, z.B. "!c tps"
# DiscordChatChannelConsoleCommandRolesAllowed: the user roles that are allowed to execute server commands from the chat channel
# DiscordChatChannelConsoleCommandWhitelist: list of commands that are able to be ran with DiscordChatChannelConsoleCommandPrefix
# DiscordChatChannelConsoleCommandWhitelistBypassRoles: list of roles that bypass the whitelist
# DiscordChatChannelConsoleCommandWhitelistActsAsBlacklist: should the command whitelist act as a blacklist instead
# DiscordChatChannelConsoleCommandExpiration: time in seconds until a sent command output is automatically removed by the bot. set to 0 to disable expiration.
# DiscordChatChannelConsoleCommandExpirationDeleteRequest: whether or not to delete the message of the person that originally issued the command
#
DiscordChatChannelConsoleCommandEnabled: true
DiscordChatChannelConsoleCommandNotifyErrors: true
DiscordChatChannelConsoleCommandNotifyErrorsFormat: "**%user%**, you tried running a command. Unfortunately, there was an error: %error%"
DiscordChatChannelConsoleCommandPrefix: "!c"
DiscordChatChannelConsoleCommandRolesAllowed: ["Developer", "Owner", "Admin", "Moderator"]
DiscordChatChannelConsoleCommandWhitelist: ["say", "lag", "tps"]
DiscordChatChannelConsoleCommandWhitelistBypassRoles: ["Owner", "Developer"]
DiscordChatChannelConsoleCommandWhitelistActsAsBlacklist: false
DiscordChatChannelConsoleCommandExpiration: 0
DiscordChatChannelConsoleCommandExpirationDeleteRequest: true

# Server startup/shutdown messages
# DiscordChatChannelServerStartupMessage: message to be sent when server starts; leave blank to disable
# DiscordChatChannelServerShutdownMessage: message to be sent when server shuts down; leave blank to disable
#
DiscordChatChannelServerStartupMessage: ":white_check_mark: **Server wurde gestarted**"
DiscordChatChannelServerShutdownMessage: ":octagonal_sign: **Server wurde gestoppt**"

# Chat channel player list command
# All the config stuff for the player list command
#
# DiscordChatChannelListCommandEnabled: whether the command is enabled
# DiscordChatChannelListCommandMessage: the command people can type to get the player list
# DiscordChatChannelListCommandFormatOnlinePlayers: the message at the beginning of the list (%playercount% will show the current player count)
# DiscordChatChannelListCommandFormatNoOnlinePlayers: "*No online players*"
# DiscordChatChannelListCommandExpiration: time in seconds until a sent player list message is automatically removed by the bot. set to 0 to disable expiration.
# DiscordChatChannelListCommandExpirationDeleteRequest: whether or not to delete the message of the person that originally requested for the player list
#
DiscordChatChannelListCommandEnabled: true
DiscordChatChannelListCommandMessage: "playerlist"
DiscordChatChannelListCommandFormatOnlinePlayers: "Aktive Spieler (%playercount%):"
DiscordChatChannelListCommandFormatNoOnlinePlayers: "**Keine Spieler online**"
DiscordChatChannelListCommandExpiration: 10
DiscordChatChannelListCommandExpirationDeleteRequest: true

# Chat channel blacklisted phrases & regex
# DiscordChatChannelBlockedPhrases: phrases which if a message is sent in the chat channel containing a phrase here, the message won't be processed
# DiscordChatChannelCutPhrases: phrases which if said in the Minecraft chat will be removed from the message before sending it to the chat channel
# DiscordChatChannelRegex: regex to filter the chat going to Minecraft by
# DiscordChatChannelRegexReplacement: replacement for above option
#
DiscordChatChannelBlockedPhrases: ["Aktive Spieler (", "**Keine Spieler online**"]
DiscordChatChannelCutPhrases: ["@everyone"]
DiscordChatChannelRegex: ""
DiscordChatChannelRegexReplacement: ""

# Player join/leave messages
# Self explanatory, set an option to blank to disable that message (: "")
#
# %displayname% = display name from things like nicknames
# %username% = raw player username
#
MinecraftPlayerJoinMessageFormat: ":bangbang: **%displayname% joined the server**"
MinecraftPlayerFirstJoinMessageFormat: ":tada: **%displayname% joined the server for the first time**"
MinecraftPlayerLeaveMessageFormat: ":x: **%displayname% left the server**"

# Player death messages
# Leave blank to disable
#
# MinecraftPlayerDeathMessageFormat: the format used when sending death messages from Minecraft to Discord
# %displayname% = display name from things like nicknames
# %username% = raw player username
# %deathmessage% = raw death message
# %world% = the name of the world the user died in
#
MinecraftPlayerDeathMessageFormat: ":skull: **%deathmessage%**"

# Unsubscribed user message forwarding
# Whether or not people who are unsubscribed from Discord chat messages will still have their messages
# sent to the chat channel, yet still not see anything from the chat channel
#
MinecraftUnsubscribedMessageForwarding: false

# Achievement messages
#
# MinecraftPlayerAchievementMessagesFormat: the format used when sending achievement messages from Minecraft to Discord; leave blank to disable
# %achievement% = message content
# %displayname% = display name from things like nicknames
# %username% = raw player username
# %world% = the name of the world the user is in
#
MinecraftPlayerAchievementMessagesFormat: ":medal: **%displayname% has just earned the achievement %achievement%!**"

# Channel topic updater
# This is all the stuff related to automatically updating the chat or console channel's topics with server information
# To disable one of the messages, make the value completely blank, i.e. ""
# or optionally to disable both of the constantly updating messages, change ChannelTopicUpdaterRateInSeconds to 0
#
# all the format options have the same available placeholders
#
# %playercount% = current player count
# %playermax% = maximum player count
# %date% = current date
# %totalplayers% = total amount of players to ever join the main world
# %uptimemins% = amount of minutes since DiscordSRV has started
# %uptimehours% = amount of hours since DiscordSRV has started
# %motd% = motto of the day of the server
# %serverversion% = server version such as Spigot-1.9
# %freememory% = free memory of the JVM in MB
# %usedmemory% = used memory of the JVM in MB
# %totalmemory% = total memory of the JVM in MB
# %maxmemory% = max memory of the JVM in MB
# %freememorygb% = free memory of the JVM in GB
# %usedmemorygb% = used memory of the JVM in GB
# %totalmemorygb% = total memory of the JVM in GB
# %maxmemorygb% = max memory of the JVM in GB
# %tps% = average TPS of the server
#
ChannelTopicUpdaterChatChannelTopicFormat: "%playercount%/%playermax% players online | %totalplayers% unique players ever joined | Server online for %uptimemins% minutes | Last update: %date%"
ChannelTopicUpdaterConsoleChannelTopicFormat: "TPS: %tps% | Mem: %usedmemorygb%GB used/%freememorygb%GB free/%maxmemorygb%GB max | %serverversion%"
ChannelTopicUpdaterChannelTopicsAtShutdownEnabled: true
ChannelTopicUpdaterChatChannelTopicAtServerShutdownFormat: "Server is offline | %totalplayers% unique players ever joined"
ChannelTopicUpdaterConsoleChannelTopicAtServerShutdownFormat: "Server is offline | %serverversion%"
ChannelTopicUpdaterRateInSeconds: 5

# Subscription messages
# Diese Nachrichten werden gesendet, wenn ein Nutzer /discord subscribe/unsubscribe/toggle benutzt
#
MinecraftSubscriptionMessagesOnSubscribe: "&bDu wirst jetzt bei Discord-Nachrichten benachrichtigt."
MinecraftSubscriptionMessagesOnUnsubscribe: "&bDu wirst nicht mehr bei Discord-Nachrichten benachrichtigt."

# Commandnachricht: /discord
# Diese Nachricht wird versendet, wenn man /discord eingibt.
#
DiscordCommandFormat: "&bTrete unserem Server bei auf discord.gg/changeintheconfig. Für Hilfe, benutze \"/discord ?\""

# Chat-Reaktionen
# 
# Diese Befehle sorgen für eine automatisierte Antwort, sofern sie ausgelöst werden.
# Bitte auf jeden Fall ändern, oder eigene hinzufügen.
# Zum Deaktivieren zu {} ändern.
#
# Die Syntax ist {"TRIGGER": "ANTWORT", "TRIGGER": "ANTWORT", ...}
#
DiscordCannedResponses: {"!ip": "example.net", "!site": "http://example.net"}

# Minecraft zu Discord: Accountverbindung
# Dies sind die Optionen, die bestimmen, wie die Verbindung zwischen Discord und Minecraft funktioniert.
#
# MinecraftDiscordAccountLinkedConsoleCommand: ein Command der ausgeführt wird, wenn die Verbindung abgeschlossen ist.
# %minecraftplayername% = Minecraft-Username des Spielers
# %minecraftuuid% = UUID des Spielers
# %discordid% = ID des Discord-Accounts
# %discordname% = Name des Discord-Accounts
#
# MinecraftDiscordAccountLinkedRoleToAddUserTo: Die Rolle, die dem Discord-Nutzer zugewiesen wird, wenn er Minecraft und Discord verbunden hat.
# MinecraftDiscordAccountLinkedSetDiscordNicknameAsInGameName: Ob der Nickname des Nutzers zu seinem Minecraft-Namen geändert werden soll.
#
MinecraftDiscordAccountLinkedConsoleCommand: ""
MinecraftDiscordAccountLinkedRoleNameToAddUserTo: "Linked"
MinecraftDiscordAccountLinkedSetDiscordNicknameAsInGameName: false

# Minecraft zu Discord: Rollensynchronisation
#
# Die Syntax ist {"in-game gruppenname": "discord-rollenname", "in-game gruppenname": "discord-rollenname", ...)
# Wenn du die Synchronisation nicht verwenden möchtest, füge einfach {} ein.
#
GroupRoleSynchronizationRolesToSynchronize: {"owner": "DISCORDROLENAME", "admin": "DISCORDROLENAME"}

# Server-Watchdog
#
# Der Server-Watchdog überprüft andauernd, wann der letzte Ingame-Tick passiert ist.
# Wenn diese Zeit das eingestellte Maximum übersteigt, wird eine Discord-Nachricht gesendet.
#
# ServerWatchdogEnabled: Ob der Watchdog überhaupt akitv ist.
# ServerWatchdogTimeout: Zeit in Sekunden bis der Watchdog eine Nachricht sendet (Der Standardwert, ab dem Spigot es als Absturz behandelt, ist 60)
#                        Minimalwert ist 10
# ServerWatchdogMessage: Die Nachricht, die im Hauptchat-Kanal gesendet wird.
#                        Für @Mentions von Benutzern "<@USERID>", z.B. "<@12345678901234567890>"
#                        Für @Mentions von Rollen "<@&ROLEID>", z.B. "<@&12345678901234567890>"
#                        Für @Mentions vom Serverbesitzer (Discord) "%guildowner%"
#                        Datum und Zeit der Meldung mit %date%
# ServerWatchdogMessageCount: Anzahl von Nachrichten, die gesendet werden. Nützlich, wenn du *wirklich* wissen magst, was los ist.
#
ServerWatchdogEnabled: true
ServerWatchdogTimeout: 60
ServerWatchdogMessage: "`%date%` Achtung: Server läuft langsam :bangbang:"
ServerWatchdogMessageCount: 3

# Synchronisierung von Bans
# Wenn ein Spieler, der Discord und Minecraft verbunden hat, von Discord gebannt wurde, kann er optional auch vom Minecraft-Server gebannt werden (in beide Richtungen).
#
# BanSynchronizationDiscordToMinecraft: Ob Spieler vom Minecraft-Server gebannt werden, wenn sie von Discord gebannt werden
# BanSynchronizationDiscordToMinecraftReason: Der Ban-Grund in Minecraft, wenn Spieler von Discord gebannt wurden.
# BanSynchronizationMinecraftToDiscord: Ob Spieler vom Discord-Server gebannt werden, wenn sie in Minecraft gebannt wurden.
#
BanSynchronizationDiscordToMinecraft: false
BanSynchronizationDiscordToMinecraftReason: "&cDu wurdest von diesem Server gebannt, da du auch vom zugehörigen Discord-Server gebannt wurdest."
BanSynchronizationMinecraftToDiscord: false
