name: DiscordSRV
version: ${project.version}
description: The most powerful, configurable, open-source Discord bridge plugin out there.
author: Scarsz & Androkai
website: https://github.com/Scarsz/DiscordSRV

main: github.scarsz.discordsrv.DiscordSRV
database: false
softdepend: [GroupManager, GroupManagerX, LuckPerms, PermissionsEx, zPermissions, HeroChat, Legendchat, LunaChat, mcMMO, Multiverse-Core, TownyChat, Vault, VentureChat]
load: STARTUP

commands:
  discord:
    description: DiscordSRV commands
    usage: /discord

permissions:
  discordsrv.admin:
    description: whether or not a player can use admin functions of the plugin
    default: false
  discordsrv.chat:
    description: whether or not the user is able to have their chat forwarded to Discord
    default: true
  discordsrv.togglesubscribe:
    description: whether or not the user is able to toggle their subscription status to Discord messages
    default: true
  discordsrv.silentjoin:
    description: whether or not to have join messages for players with this permission to be silenced
    default: false
  discordsrv.silentquit:
    description: whether or not to have quit messages for players with this permission to be silenced
    default: false
