main: com.scarsz.discordsrv.DiscordSRV
version: 8.9
name: DiscordSRV
softdepend: [HeroChat, Vault]

commands:
  discordsrv:
    description: DiscordSRV commands
    usage: /discordsrv

permissions:
  discordsrv.chat:
    description: whether or not the user is able to have their chat forwarded to Discord
    default: true