name: DiscordSRV
version: ${project.version}
description: The most powerful, configurable, open-source Discord bridge plugin out there.
author: Scarsz & Androkai
website: https://github.com/Scarsz/DiscordSRV

main: github.scarsz.discordsrv.DiscordSRV
database: false
softdepend: [GroupManager, GroupManagerX, LuckPerms, PermissionsEx, zPermissions, HeroChat, Legendchat, LunaChat, mcMMO, Multiverse-Core, TownyChat, Vault, VentureChat]

commands:
  discord:
    description: DiscordSRV commands
    usage: |
           /discord - Show the invite link of the Discord server
           /discord help/? - Show command list
           /discord subscribe - Subscribe for messages from Discord
           /discord unsubscribe - Unsubscribe for messages from Discord
           /discord toggle - Toggle subscribtion for messages from Discord
           /discord link - Link Minecraft account with Discord account
           /discord clearlinked - Remove link between Minecraft and Discord account
           /discord linked - Show information about linking status
           /discord bcast - Broadcast a message to Discord
           /discord setpicture - Set the bot''s avatar
           /discord debug - Send debug information to Gist
           /discord reload - Reload the plugin

permissions:
  discordsrv.admin:
    description: whether or not a player can use admin functions of the plugin
    default: false
  discordsrv.chat:
    description: whether or not the user is able to have their chat forwarded to Discord
    default: true
  discordsrv.togglesubscribe:
    description: whether or not the user is able to toggle their subscription status to Discord messages
    default: true
  discordsrv.silentjoin:
    description: whether or not to have join messages for players with this permission to be silenced
    default: false
  discordsrv.silentquit:
    description: whether or not to have quit messages for players with this permission to be silenced
    default: false
