name: DiscordSRV
version: ${project.version}
description: The most powerful, configurable, open-source Discord bridge plugin out there.
author: Scarsz
website: https://github.com/Scarsz/DiscordSRV

main: com.scarsz.discordsrv.DiscordSRV
database: false
softdepend: [HeroChat, Legendchat, LunaChat, Multiverse-Core, TownyChat, Vault, VentureChat]
load: STARTUP

commands:
  discord:
    description: DiscordSRV commands
    usage: /discord

permissions:
  discordsrv.chat:
    description: whether or not the user is able to have their chat forwarded to Discord
    default: true
