main: com.scarsz.discordsrv.DiscordSRV
version: 8.1
name: DiscordSRV
softdepend: [Vault]

commands:
  discordsrv:
    description: DiscordSRV commands
    usage: /discordsrv
    permission: discordsrv